### ISSUE TITLE
Detection box

### ISSUE THREAD

**Issue by heyraselyn** [gurkirt/realtime-action-detection#41]
Not really an issue, but I was wondering if the detection box is supposed to be this big as opposed to the ground truth (red box)? I just applied your trained model and was able to achieve the results quantitatively, but this doesn't look like the one in your video demo. 

<img width="314" alt="Screen Shot 2019-05-13 at 11 39 51 AM" src="https://user-images.githubusercontent.com/50562990/57592897-f4303680-7573-11e9-8d34-a494a1f82762.png">

**Comment by gurkirt** [comment]
Check if you have taken care of output properly. 
This doesn't look right.

I don't remember exactly but the output is supposed to be in the format of x1, y1, x2, y2, not x1,y1, w,h.

Cross check it and predicted should is pretty close to GT box. most of the errors are due to temporal linking and trimming not localisation on the person.

**Comment by heyraselyn** [comment]
I see. Thanks!
